# Generated by Django 3.2.2 on 2023-09-19 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('nationality', models.CharField(blank=True, max_length=25, null=True, verbose_name='country')),
                ('timezone', models.CharField(blank=True, max_length=60, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('current', 'Current')], default='savings', max_length=15)),
                ('account_number', models.CharField(default='6031979050', max_length=10, unique=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('currency', models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro'), ('¥', 'Yen')], default='$', max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overdraft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('site_domain', models.CharField(help_text='site url/link i.e miningsite.com', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('interest_rate', models.IntegerField(default=2, help_text='IN PERCENTAGE(%)')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_address', models.CharField(blank=True, help_text='TRC20', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(blank=True, choices=[(None, None), ('mastercard', 'Mastercard'), ('visa', 'Visa'), ('verve', 'Verve')], default=None, max_length=10, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('card_pin', models.CharField(blank=True, max_length=4, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(default='null', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase'), ('loan', 'Loan')], default='transfer', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.TextField(blank=True, help_text='Comment', max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('transaction_number', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date And Time Initiated')),
                ('from_user', models.ForeignKey(help_text='Initiator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=1, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_in_months', models.IntegerField()),
                ('remark', models.TextField(blank=True, max_length=2500)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('monthly_returns', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_returns', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/kyc')),
                ('id_type', models.CharField(blank=True, choices=[(None, None), ('national id', 'National ID'), ('drivers license', 'Driver License'), ('international passport', 'International Passport')], default=None, max_length=30, null=True)),
                ('id_number', models.CharField(blank=True, max_length=60, null=True)),
                ('id_upload', models.ImageField(blank=True, null=True, upload_to='images/kyc')),
                ('status', models.CharField(choices=[('null', 'Null'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='null', max_length=8)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='images/crypto')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
