# Generated by Django 3.2.2 on 2023-09-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='method',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('usdt', 'USDT(TRC20)')], default='usdt', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(default='3169494193', max_length=10, unique=True),
        ),
    ]
