# Generated by Django 3.2.2 on 2023-09-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0004_auto_20230929_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('declined', 'Declined')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
