# Generated by Django 3.2.2 on 2023-10-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingapp', '0006_loan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('funding', 'Account Funding'), ('card', 'Virtual Card')], default='funding', max_length=12)),
                ('method', models.CharField(choices=[('bank transfer', 'Bank Transfer'), ('bitcoin', 'Bitcoin'), ('usdt', 'USDT(TRC20)')], default='usdt', max_length=20)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='images/payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='account_bank',
            field=models.CharField(blank=True, help_text='Funding Account Bank', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='account_name',
            field=models.CharField(blank=True, help_text='Funding Account Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='account_number',
            field=models.CharField(blank=True, help_text='Funding Account Number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('£', 'Pound'), ('€', 'Euro'), ('¥', 'Yen')], default='$', max_length=1),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='iban_code',
            field=models.CharField(blank=True, help_text='Funding Account IBAN Number (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Funding Account Swift Code (optional)', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='IN PERCENTAGE(%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(blank=True, choices=[(None, None), ('national id', 'National ID'), ('drivers license', 'Driver License'), ("int'l passport", "Int'l Passport")], default=None, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CryptoTransaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
